### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by tjakubo2** [Knils/atom-tabletopsimulator-lua#29]
This is a list of small things I've observed. Low impact, no idea how hard would be to touch on these but figured would be worth noting :)

1. Functions declared like `myFun = function(args)` aren't registered with the "display/jump/select/... function" feature. Of course they work properly with the equivalent syntax sugar ``function myFun(args)``.

2. 'else' statement triggers autocomplete 'editNotebookTab' which can be quite annoying when doing if-elses.

3. I think at some point the "restore last opened script file and cursor position in it after save&play" functionality was broken. I may be misusing the thing, but looks like it's not working. Also related, maybe instead of a "Only open Global on save&play", we could get "Only open the file you were in last on save&play"? Or perhaps Global loaded + last file opened. 

4. The standard 'table' library (or rather the part of it Moonshine implements) is not autocompleting, same with 'string'. We can list methods available in TTS with something like ``for name in pairs(table) do print(name) end``. Would you be up for adding those, even if they aren't exactly part of TTS API? I could start on that I think. We do have 'math' library completion so that's almost the same thing.

**Comment by tjakubo2** [comment]
Pinging the mastermind @onelivesleft

**Comment by onelivesleft** [comment]
1. I've been noticing this myself, haven't tried to make it work, will see how doable it is when I do.
1. I'll check this out
1. Are you noticing the cursor not working now?  I thought I had it ironed out in the newest patch.  Will check.  I've not tried ticking both those options at once; I guess the desired outcome would be to open global and all the non-tts folder files you had open, but no other tts folder files.
1. Yeah, can add them.  Same with string, if it's not there already.

**Comment by tjakubo2** [comment]
@onelivesleft 
Would it be possible to make Save&Play also save all files in the editor like it does with TTS script files? Sadly any edits on those are currently lost if we don't manually do Save or File -> Save All.

**Comment by onelivesleft** [comment]
It *should* be saving everything. I'll check it out.

On 1 Sep 2017 12:23 pm, "tjakubo2" <notifications@github.com> wrote:

@onelivesleft <https://github.com/onelivesleft>
Would it be possible to make Save&Play also save all files in the editor
like it does with TTS script files? Sadly any edits on those are currently
lost if we don't manually do Save or File -> Save All.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Knils/atom-tabletopsimulator-lua/issues/29#issuecomment-326556537>,
or mute the thread

**Comment by onelivesleft** [comment]
Next patch will address these issues as follows:

1. I'm not going to try to parse functions declared in this manner, for a couple of reasons: (1) functions used like this are typically being used anonymously, so do not require it, (2) it would be extremely complicated to do, and effectively impossible to do completely: if I have a function ```lambda = function(x) return x+1 end``` then I index it as lambda.  If I then have a line of code saying ```theta = lambda``` I index it as theta too... The plugin would have to actually parse Lua to determine this stuff.
So instead I'm leaving it as is, which is actually a feature: if you do not want your function to turn up in the index then declare it in this manner, and if you do want it to be indexed then use the standard declaration style.

1. I swear I noticed this myself but on testing couldn't reproduce.  I've rewritten the code that short-circuits the autocomplete on Lua keywords, so hopefully will no longer be an issue.

1. This is still an experimental feature.  I've changed it so instead of reopening non-TTS files it simply does not close them in the first place.  Let's see how that works out.

1. Added string, table, bit32 and dynamic, so that should be everything now present.  This was actually really easy to do with the [console++](https://github.com/onelivesleft/TTSConsole) module; I could just ```ls sys``` then ```ls -f string```, ```ls -f table```, etc:
![lsexample](https://user-images.githubusercontent.com/17881109/30254523-242ac656-9692-11e7-895b-a53744753a09.png)

**Comment by onelivesleft** [comment]
N.B. You are not the only person who complained about it failing to save files, but I have been mostly unable to reproduce that behaviour.  I did realise that if you hit Save And Play more than once, so that you activated one S&P while it was still performing the previous S&P it could mess up, and I've fixed that.  Hopefully that was the issue, but anyway I've left console.log statements in to display when it starts a Save & Play, what files it saves, and when it's done, so you'll be able to check what's happened.
